import os
import subprocess
import shutil
import sys

def process_fpocket(input_folder, output_folder):
    # Ensure the output directory exists
    os.makedirs(output_folder, exist_ok=True)

    # Process each PDB file in the input folder
    for pdb_file in os.listdir(input_folder):
        if pdb_file.endswith(".pdb"):
            input_path = os.path.join(input_folder, pdb_file)

            # Run fpocket
            result = subprocess.run(
                ["fpocket", "-f", input_path],
                capture_output=True, text=True
            )

            print(f"Processing {pdb_file}:\n{result.stdout}")  # Print stdout
            print(f"Errors (if any):\n{result.stderr}")  # Print stderr

            # Determine the output directory created by fpocket
            protein_name = os.path.splitext(pdb_file)[0]  # Get protein name (without extension)
            fpocket_out_dir = f"{protein_name}_out"  # Folder name generated by fpocket

            # Move the entire output folder to the desired location
            source_dir = os.path.join(input_folder, fpocket_out_dir)
            destination_dir = os.path.join(output_folder, fpocket_out_dir)

            if os.path.exists(source_dir):
                # Move the folder
                shutil.move(source_dir, destination_dir)
                print(f"Moved {fpocket_out_dir} to {output_folder}")
            else:
                print(f"Output directory not found for {protein_name}")

if __name__ == "__main__":
    if len(sys.argv) != 3:
        print("Usage: python script.py <input_folder> <output_folder>")
        sys.exit(1)

    input_folder = sys.argv[1]
    output_folder = sys.argv[2]

    process_fpocket(input_folder, output_folder)
